language: ruby
sudo: true
env:
  global:
    - rvmsudo_secure_path: 0
rvm:
  - 1.9.3
  - 2.0
before_install:
  - gem install fpm-cookery
  - gem install executable-hooks
install:
  - find ./ -mindepth 1 -maxdepth 1 -type d | while read tool; do cd "${tool}"; rvmsudo $(which fpm-cook) --debug; done

# deb packages are created under ./*/pkg/*.deb
