language: ruby
sudo: true
env:
  global:
    - rvmsudo_secure_path: 0
    - GH_REF: github.com/${TRAVIS_REPO_SLUG}.git
    - secure: "kzZNUDXaB9dO/at6ZPbXD9J0CQSb6WkQicO0fvG5VyBAKtLf1h3cmn7DxXfkUn11ZN5jt81P3oQUfSXrD5WddNlf2cu+14cS821POvU69vFizyHLgDpCzvEwWg6UJKMEzuO7lEZqbZl4qaxN8kWlC3jDlSvO6NY+Cn3i6kLO8vS8/n0u4B+wJP/y7sW3OVin4rQsx/+KBU/YwI3hqs0v43D98LH+hHWFw+mIqOcjCX2jKZChPI7DaqRv2A2Y+/VCeBBZRoo1YmxtLtp+23+m6SSZT/PS2DXexBmAIQM63DCkHFgr5g2vWNWqI2e1LMWixkrgBAnIy+mLsadXnpSHh5gh5QWEAa+FbS1DB3xGsLU5aDkb0o1SYVuMo1WpljPJxknmxmANFy1HdHqhmVTHg2W7ioBEtyFdQx39TKq4tOrEu36Xy7JIJhpisYp3ZeDCL9pNlYYUdPLDT0EhVC1a+IQb4AXnGbTOFHgrKVDsJ+n0EIDSFP7OrzMcr8xfzerXiomFFmiCLpEGGKUgD3rCJW1GuB0js/vQi8USc+PERjfz79dkZvjOGreHDLrPABLnOolZpdmtxvV3RMinqq0OaXFpNhZUw00yBEkGtJ0DI0y+I29Zej0hZXZK3pvHEELByNkzmyQFDLBcgNSXrKI5mpmnO5iaQmf3YcS32eTcnJU="
rvm:
  - 1.9.3
  - 2.0
before_install:
  - gem install fpm-cookery
  - gem install executable-hooks
  - wget https://github.com/github/git-lfs/releases/download/v0.6.0/git-lfs-linux-amd64-0.6.0.tar.gz
  - tar xvzf git-lfs-linux-amd64-0.6.0.tar.gz
  - cd git-lfs-0.6.0 && sudo ./install.sh
script:
  - travis_wait 90 ./.travis.build
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then bash ./deploy-ghpages.sh; fi
