language: ruby
sudo: true
env:
  global:
    - rvmsudo_secure_path: 0
rvm:
  - 1.9.3
  - 2.0
before_install:
  - gem install fpm-cookery
  - gem install executable-hooks
script:
  - cd amos; rvmsudo $(which fpm-cook) --debug;

# deb packages are created under ./*/pkg/*.deb
