language: ruby
sudo: required
rvm:
  - 1.9.3
before_install: 
  - sudo $(which gem) install fpm-cookery
script:
  - cd cufflinks && sudo $(which fpm-cook) clean && sudo $(which fpm-cook)
#  - find ./ -maxdepth 1 -type d -exec sh -c 'cd "$0" && fpm-cook' {} \;
#  - cd amos && fpm-cook

# deb packages are created under ./*/pkg/*.deb
