language: ruby
sudo: true
env:
  global:
  - rvmsudo_secure_path: 0
rvm:
- 1.9.3
- 2.0
before_install:
- gem install fpm-cookery
- gem install executable-hooks
script:
- travis_wait 90 ./.travis.build
after_success:
- chmod 755 ./pkg/*.deb
before_deploy:
- export RELEASE_PKG_FILE=$(ls ./pkg/*.deb)
- echo "deploying ${RELEASE_PKG_FILE} to GitHub releases"
deploy:
  provider: releases
  api-key:
    secure: aaLEJnOyjMEl8PRPO6tpsm/D3Ww8avFWKhB26OkFbvn83SJvMrtRmRa/OsURlDJwg7GoCuAxcS/9bgysFA6rHnO0X9I5Lg/mBfSTvv3bTrBFC8bdXfjF2Tb3DCMNwNcQw+OvYMxgeENzR+ghhJeaFexQpvP/xCdpeeLISR+BRQ6XO1NEuN3p9k60MZjtQm0qwYLBFk0fUWmy4uMMINsPGcFA3ww4exk7/Y4BWhB3OPetnsmeZDCPvBrFkGgp5ACPd2dtiO2tDJM98v6R50NsV9G3xi7Hp1Pjp66wwgoAk9QehP+cFEUU/Yz72Xddbmj6U4uyH+bEPrfC+LKU6bKresYVN5VFTLieY6k7wEVLL/Q4D/KFWr9LZYFXjnzuT1LeYl/73xm591t3teM5EylbLhgLmJXRVRPwh7UcbF99chtfIIN8tsENHrDpGXLHAVy1l5F11h94jQTzKDvKtBv0+Rtw8xGaUogZ5FIOdQqO5uPdN6EtN6FqBB+bLX/oDhT9Gd7Ep8Q38AN3X5z6Z12pdIryMQC1Zl6XWYri9Y0HOBw/zR/ARKiuiNKxf54X4kq9U/c2qDYmIRhSZEVqHowAhxH9dYpV8USvFhKL81rS9q4rBYePJwB2a/iiSSlbISEj8YOrE3bcNZZlkcDkzw1nw7BGJcVFxSxmX6pSmo7+7Yc=
  file_glob: true
  file: ./pkg/*.deb
  skip_cleanup: true
  on:
    tags: true
