language: ruby
rvm:
  - 1.9.3
install: gem install fpm-cookery
script:
  - cd cufflinks && sudo fpm-cook
#  - find ./ -maxdepth 1 -type d -exec sh -c 'cd "$0" && fpm-cook' {} \;
#  - cd amos && fpm-cook

# deb packages are created under ./*/pkg/*.deb
