language: ruby
sudo: true
env:
  global:
    - rvmsudo_secure_path: 0
rvm:
  - 1.9.3
  - 2.0
before_install:
  - gem install fpm-cookery
  - gem install executable-hooks
script:
  - travis_wait ./.travis.build
