language: ruby
sudo: true
env:
  global:
    - rvmsudo_secure_path: 0
rvm:
  - 1.9.3
  - 2.0
before_install:
  - gem install fpm-cookery
  - gem install executable-hooks
script:
  - travis_wait 90 ./.travis.build
before_deploy:
  - export RELEASE_PKG_FILE=$(ls ./pkg/*.deb)
  - echo "deploying ${RELEASE_PKG_FILE} to GitHub releases"
deploy:
  provider: releases
  api-key:
    - secure: "pUuEunh1q+08PbHFUK1YO//sdkosivaN+zgdEHX9VA1UH6lWpZipR0ww2vWh++NDUOiJS9WD7kJ8c0wcPd513KpOGhpijnb5P8WhQJ56V06zoA0E42/FWk3+0oH7gGkVb7GqWvyZUvFvdBf8nPO4wG5u/QSFqUixGpWrmpW//X8Sn73aId6tefO75/GA3gBKxkdY0Y+Pj2w/W41w1vI++NIsFkerZIYEUpO03zAX/3GVdKbF3bQhoqJe778mqLpVhSSZ0wq+00fcz9Nt4+axpZ2hn2p8jFVB+KRDXls9eV7OL1n0i4KxvlPtTeAHUKYI1bp44wxgrbskNEhHZCPhEUCmPxwz70NO3mGzMeGwlBZoA4RtAHgqHxW9rZDtbRu7bT1ymn9p/aD2zRhzqKoqbGrlRE/Yiw8mOvimZW8VG6Koj49TvewBoPhaE7gqaAZ6MhK4Cw8QyB40XiivVf8V2AF4HlIhDl3bG0xrNB+tFHhKbZC5f97yi68E6QJ/AYpHX0Pj6rv8FxjzqR+Bq1Crc8VaKstUVo8Xnvhgmxkcr7Wltp3mbEeheVOvZR2lZ1VvxueTBIpDBuTHCvMesCQ450MuQigSuDednOfjL/X8ApO6c181OpbdcM0WzVC5wVdny0KjZWIJrvt2VzvCwATlrcF3jWqJPgkQVJsMJP02lQk="
  file_glob: true
  file: ./pkg/*.deb
  skip_cleanup: true
  on:
    tags: true
