language: ruby
sudo: true
env:
  global:
    - rvmsudo_secure_path: 0
rvm:
  - 1.9.3
  - 2.0
before_install:
  - gem install fpm-cookery
  - gem install executable-hooks
script:
  - git --no-pager diff --name-only ${TRAVIS_COMMIT_RANGE##*...} ${TRAVIS_COMMIT_RANGE%...*} | fgrep recipe.rb | while read recipe; do rvmsudo $(which fpm-cook) package --target deb --platform ubuntu --pkg-dir ./pkg "${recipe}" || exit; done
#  - find ./ -maxdepth 2 -type f -name recipe.rb | while read recipe; do rvmsudo $(which fpm-cook) package --target deb --platform ubuntu --pkg-dir ./pkg "${recipe}" || exit; done
#  - cd amos; rvmsudo $(which fpm-cook) --debug;

