language: ruby

rvm:
  - 1.9.3
  - 2.0

before_install:
  - rvm use system
  - ruby --version
  - rvm --version
  - rvm get stable
  - rvm --version
  - gem install fpm-cookery
  - gem install executable-hooks
  - gem regenerate_binstubs

install:
  - which fpm-cook
  - which ruby_executable_hooks
  - fpm-cook --help
  - cd cufflinks; sudo $(which fpm-cook) --debug; cd ../
  - cd igv; sudo $(which fpm-cook) --debug; cd ../
#  - find ./ -mindepth 1 -maxdepth 1 -type d -exec sh -c 'cd "$0" && fpm-cook --debug' {} \;

# deb packages are created under ./*/pkg/*.deb
