language: ruby

rvm:
  - 1.9.3
  - 2.0

before_install:
  - gem install fpm-cookery

script:
  - fpm-cook --help
  - find ./ -mindepth 1 -maxdepth 1 -type d -exec sh -c 'cd "$0" && sudo $(which fpm-cook) install-deps && fpm-cook --debug' {} \;

# deb packages are created under ./*/pkg/*.deb
