language: ruby

rvm:
  - 1.9.3
  - 2.0
env:
  global:
    - rvmsudo_secure_path: 0

before_install:
  - gem install fpm-cookery
  - gem install executable-hooks

install:
  - cd cufflinks; rvmsudo fpm-cook --debug; cd ../
  - cd igv; rvmsudo fpm-cook --debug; cd ../
#  - find ./ -mindepth 1 -maxdepth 1 -type d -exec sh -c 'cd "$0" && fpm-cook --debug' {} \;

# deb packages are created under ./*/pkg/*.deb
