language: ruby
sudo: true
env:
  global:
  - rvmsudo_secure_path: 0
rvm:
- 1.9.3
- 2.0
before_install:
- gem install fpm-cookery
- gem install executable-hooks
script:
- travis_wait 90 ./.travis.build
after_success:
- sudo chmod 755 ./pkg/*.deb
before_deploy:
- export RELEASE_PKG_FILE=$(ls ./pkg/*.deb)
- echo "deploying ${RELEASE_PKG_FILE} to GitHub releases"
deploy:
  provider: releases
  api-key:
    secure: MfWqVrv2ixwbWafYHssBsza7TB7+7Lh9piQvX5brqALtJ4y1QdbB/l2geArflLv3W1OWti3EBuf2RXVdZZ26Fr3hyjTxJU562bpJ3cVGcyg+ty+XufZpXndCea6ol9EX1oaEIQxflaqZzPxQxGxzgRHfjsUB1xLOhT0OWfV8lRhrz1O74qGexaENu11J1wtU8sQi4xJWgGnd69U985VsglNf04/f7alYhKXBPiC5fn2Y2XNmtT834fMEOz5nyhjzrTKE4NZ4oQq6DgcLivwTiAD5xIj57V6KW/t93d4L98++RTj+1WqoNebiTLG5gD8F5T+7mmHw1EW9Cx7HgZNu/GMrDplPVMC9ur98DfwawplIXGtUKNBBEqvtN6O9sxxfbvJmMPEwuVhca97pnpzQA28MEK+qw3U+H3csTctHDfRS0MtyjEIsyAp0Gc8kKOU5VcIikhu5jph7lV1M3hxFoZSdZxF/IW0NADAI2bwMoLAfhqusJrKHIrn/clxckzhpTZTumjXr1WX3uYAs/hzCs2Uci7zSHs7hPmWrc2lh6OiNXO7MKKOQdIw0QkQ1kulHUYT8LujXFNTcfdEsk7ErjJK6tBLcsClgO3Xm3IsuI0Kb81X+K/CZzL+cVwEChNJtKPtNmi5EBjWWiPYgO7g86te/axHsAZjGjk6fhGWILTU=
  file_glob: true
  file: ./pkg/*.deb
  skip_cleanup: true
  on:
    tags: true
